# BASICS

In [6]:
a=5
print(a)

5


In [7]:
#hello this is saurav first time coding in python
a=10
print(typeof(a))

NameError: name 'typeof' is not defined

In [8]:
a=10
print(type(a))



<class 'int'>


In [9]:
a=1+6j
print(type(a))

<class 'complex'>


In [10]:
a=false
print(typeof(a))

NameError: name 'false' is not defined

In [11]:
a="Hello this is my first ml lab'

print(a)

SyntaxError: unterminated string literal (detected at line 1) (1296511975.py, line 1)

In [12]:
a='hello this is me in my first ml lab'
print(a)


hello this is me in my first ml lab


In [ ]:
#press esc+a to add a cell above the currect cell

In [13]:
a='''this is a multi line string
ok this is different form of strings '''
print(a)

this is a multi line string
ok this is different form of strings 


In [14]:
#press esc+b to add a cell below the current cell



This is the array in the python

In [15]:
a=[100,20,20,50]
print(a)

[100, 20, 20, 50]


# List , tupple and dictionary in python

In [16]:
fruits=["apple","banana","mango"]
print(fruits)
print(type(fruits))
print(fruits[0])

['apple', 'banana', 'mango']
<class 'list'>
apple


In [17]:
t=(10,50,60)
print(t)
print(type(t))

(10, 50, 60)
<class 'tuple'>


In [22]:
t={10,20,30,40,30,10}
print(t)
print(type(t))

{40, 10, 20, 30}
<class 'set'>


In [23]:
d={"mango":150,"apple":250,"orange":"not available"}
print(d)
print(type(d))

{'mango': 150, 'apple': 250, 'orange': 'not available'}
<class 'dict'>


# operators

In [24]:
a=10
b=-11
print(a+b)
print(a*b)
print(a-b)
print(a/b)#this gives the decimal value 
print(a//b)#this gives the floor value 
print(a**b)

-1
-110
21
-0.9090909090909091
-1
1e-11


# Conditional stataments

In [26]:
a=10
if(a>0):
    print("positive")
else:
    print("negative")

positive


# Loops

In [3]:
i=1
while(i<=10):
    print(i)
    i+=1

1
2
3
4
5
6
7
8
9
10


In [5]:
a=range(10)
print(a)
print(type(a))

range(0, 10)
<class 'range'>


In [8]:
a=list(range(1,100,2))#first argument is the initialising value and second is limit and third is incrementor
print(a)
print(type(a))

[1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99]
<class 'list'>


In [11]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [12]:
fruits=["apple","banana","mango"]
for fruit in fruits:
    print(fruit)

apple
banana
mango


# NUMPY

In [13]:
import numpy as np

In [15]:
arr=np.array([1,2,3,4,5,6])
print(arr)
print(type(arr))
print(arr.shape)

[1 2 3 4 5 6]
<class 'numpy.ndarray'>
(6,)


In [18]:
arr=np.array([[10,20],[10],[10,20,30]])#this does not accepts non homogenous size of array means this creates static array not not the dynamic one
print(arr)
print(arr.shape)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

## numpy array special functions

In [19]:
arr=np.array([[10,20,100],[10,40,30],[10,20,30]])
print(arr)
print(arr.shape)

[[ 10  20 100]
 [ 10  40  30]
 [ 10  20  30]]
(3, 3)


In [21]:
arr=np.eye(4)
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [26]:
arr=np.zeros((4,4))# . is there because python's defualt data type is float value inlike cpp
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [27]:
arr=np.zeros((4,4),dtype=np.int64) #do this to get int value
print(arr)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [28]:
arr=np.eye(4,dtype=np.int64)
print(arr)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [45]:
random=np.random.rand(2,3)#how to generate a random array having values between 0 and 1
print(random)

[[0.19950046 0.23000325 0.10215899]
 [0.36576906 0.41516533 0.56004455]]


In [39]:
random=np.random.randint(1000 ,100000 ,size=(5,10)) #how to generate a random array any between any range
print(random)


[[27541  4248 44313 49363 15630 61745 93282 16075 71335 62644]
 [22636 57018 24475 64161 25014 29614 58606 30983 44434 52517]
 [30941 46955 28436 87195 57852 11051 84606 52575 38870 82011]
 [71071 63370 66171 49192 67254 10238 94525 94130 58273 16933]
 [95388  3276 29900 65688 92479 55141 80512 35240 82310 40614]]


In [40]:
random[:,1]=10 #this is  used to allocate a single value to any column or row syntaX {NAME[ROW_IDX1,ROW_IDX2... : ,COL_IDX1,COL_IDX2...]=VALUE}
print(random)

[[27541    10 44313 49363 15630 61745 93282 16075 71335 62644]
 [22636    10 24475 64161 25014 29614 58606 30983 44434 52517]
 [30941    10 28436 87195 57852 11051 84606 52575 38870 82011]
 [71071    10 66171 49192 67254 10238 94525 94130 58273 16933]
 [95388    10 29900 65688 92479 55141 80512 35240 82310 40614]]


In [83]:
x=np.array([[1,2,3],[4,5,6]])
y=np.array([[7,8,9],[10,11,12]])
print(x+y)
print(np.add(x,y))
print(np.subtract(x,y))
print(np.multiply(x,y))
print(np.divide(x,y))

[[ 8 10 12]
 [14 16 18]]
[[ 8 10 12]
 [14 16 18]]
[[-6 -6 -6]
 [-6 -6 -6]]
[[ 7 16 27]
 [40 55 72]]
[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


In [56]:
print(np.sqrt(x))

[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]


### Cross and dot multiplication

In [81]:
print(x.dot(y))#size should follow the rules of array multiplication

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [60]:
x=np.array([1,2,3,4])
y=np.array([[5],[6],[7],[8]])
print(x.dot(y))

[70]


### operation on all element of array 

In [76]:
print(x+4)#add four to every element
print(x*2) # multiply every value by 2
print(x-2) #subtract 2 form every value
print(x/2) # divides every value by 2

[5 6 7 8]
[2 4 6 8]
[-1  0  1  2]
[0.5 1.  1.5 2. ]


In [65]:
print(np.add(y,x)) #addition when size is not same 

[[ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]]


In [75]:
print(sum(x)) #prints the sum of all elements in the array from already available inbuilt fucntion
print(np.sum(x))

print(np.sum(x,axis=0)) # sum coloum wise
print(np.sum(y,axis=1)) # sum row wise

10
10
10
[5 6 7 8]


### Array stacking and resizing/reshaping

In [87]:
print(x)
x=x.reshape(3,2)
print(x)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [93]:
x=x.reshape(-1,6)
print(x)

[[1 2 3 4 5 6]]


In [96]:
a=np.arange(10)+10
print(a)

[10 11 12 13 14 15 16 17 18 19]


In [103]:
m=[1,2,3,4,5,6,7]
np.random.shuffle(m)
print(m)
np.random.seed(1)#this will give same  random sequence everytime
np.random.shuffle(m)
print(m)

[3, 4, 5, 2, 7, 1, 6]
[6, 5, 4, 3, 7, 2, 1]


In [104]:
# Define two 1D arrays
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

# Vertical stacking (row-wise)
vertical_stack = np.vstack((array1, array2))

# Horizontal stacking (column-wise)
horizontal_stack = np.hstack((array1, array2))

print("Vertical Stack:\n", vertical_stack)
print("Horizontal Stack:\n", horizontal_stack)

Vertical Stack:
 [[1 2 3]
 [4 5 6]]
Horizontal Stack:
 [1 2 3 4 5 6]


In [1]:
#explore random choice ,random,randn function also